WIP: feat: test whether page config works well before taking snapshots
perfsee/perfsee pull request #162
Opened 2022-10-21 09:52 UTC by lizimeow

<img width="728" alt="image" src="https://user-images.githubusercontent.com/11516663/197167247-d20791e3-5be6-44ba-8581-4b82b33ea97c.png">
close #107 

the ui need to be improved... and this PR is based on #8

2022-10-25 08:31 UTC, EYHN commented on packages/platform-server/src/modules/snapshot/service.ts
> +        await this.redis.mset(key, 'pending')
this.redis.set(key, 'pending', 'EX', /* 7 days */ 3600 * 7 * 24)

2022-10-25 09:14 UTC, EYHN requested changes

2022-10-25 09:14 UTC, EYHN commented on packages/platform/src/modules/project/settings/settings-common-comp.tsx
> +          <span>Restore</span>
use `enable` maybe more clear

2022-10-26 07:49 UTC, forehalo commented
reorganize the commit messages @lizimeow

2022-10-26 09:34 UTC, forehalo commented on packages/platform-server/src/utils/get-lh-run-data.ts
> +    throttle: throttle ?? {},
why do we need throttle here?

2022-11-07 03:34 UTC, EYHN approved these changes

2022-11-08 09:44 UTC, merged