fix(platform): unable to delete user from group
perfsee/perfsee pull request #348
Opened 2023-03-14 10:26 UTC by lizimeow

2023-03-14 10:42 UTC, EYHN approved these changes

2023-03-14 10:43 UTC, EYHN requested changes

2023-03-14 10:43 UTC, EYHN commented on packages/platform/src/modules/group/analysis/bundle-score-chart.tsx
> +          <p>Created: {time}</p>
dayjs(token.createdAt).format('YYYY/MM/DD HH:mm')

2023-03-14 10:52 UTC, forehalo approved these changes

2023-03-15 02:49 UTC, EYHN approved these changes

2023-03-15 02:50 UTC, merged