feat: insight for lcp
perfsee/perfsee pull request #472
Opened 2023-08-31 10:42 UTC by DomonJi

FEATURE:
<img width="1238" alt="image" src="https://github.com/perfsee/perfsee/assets/9986655/5ca254bf-ee84-4242-bc49-c247b8899bfd">
<img width="2524" alt="image" src="https://github.com/perfsee/perfsee/assets/9986655/177328e1-7688-4294-850e-d444835c7edf">

https://github.com/perfsee/perfsee/assets/9986655/a499159a-8249-4c70-8634-859772f3f60d

TODO:
- [] source analysis for lcp

2023-08-31 10:50 UTC, DomonJi commented on packages/flamechart/src/components/flamechart-view-container.tsx
> -      const [selectedFrame, setSelectedFrame] = useState<FlamechartFrame | null>(null)
@EYHN I put this state outside to make the selectedFrame controllable, which may have breaking changes to other users.

2023-09-06 07:52 UTC, EYHN requested changes

2023-09-06 07:52 UTC, EYHN commented on packages/flamechart/src/components/flamechart-group-container.tsx
> +              disableDetailView={index !== profiles.length - 1}
users can hide the flamechart and the details view will also be hidden, so the detail view should be enabled in the last visible split.

You can calculate the last visible split
```
let lastVisibleSplit = -1
for (let i = splitCollapsed.length - 1; i >= 0; i--) {
  if (splitCollapsed[i]) {
    lastVisibleSplit = i
  } else {
    break
  }
}
lastVisibleSplit += 1
```

2023-09-06 07:52 UTC, EYHN commented on packages/flamechart/src/components/flamechart-group-container.tsx
> -            {selectedFrame && <DetailView frame={selectedFrame} theme={globalTheme} />}
Make it an option to select this old simple detail view

2023-09-06 07:52 UTC, EYHN commented on packages/flamechart/src/lib/profile-search.ts
> +  getMatchForFrame(frame: FlamechartFrame): FuzzyMatch | null
Why this change necessary?

2023-09-06 08:01 UTC, DomonJi commented on packages/flamechart/src/lib/profile-search.ts
> +  getMatchForFrame(frame: FlamechartFrame): FuzzyMatch | null
Used to match for frame's start time and endTime

2023-09-06 08:42 UTC, EYHN approved these changes

2023-09-06 08:47 UTC, merged